1. try catch的捕获异常机制 - _catch_对象会被添加到作用域链的最前端，在活动对象和全局对象之前

2. 怎么理解JS中的循环语句，c/c++中循环结束会被销毁，但是JS中的循环无法创建本地上下文？？？

   1. ```js
      for (var k in {a: 1, b: 2}) {
        alert(k);
      }
      alert(k); // 尽管循环已经结束，但是变量“k”仍然在作用域中
      ```

   2. ```js
      for (var i = 0; i < 10; i++) {
          setTimeout(()=>{
               console.log(i)
           })
      }
      ```

   3. 

